package Jframes;

import javax.swing.JOptionPane;
import Clases.*;
import persistencia.*;
import Proyecto_p2.Main;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author agusm
 */
public class AddCiruja extends javax.swing.JPanel {

    /**
     * Creates new form AddArtistaa
     */
    public AddCiruja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        specialtyField = new javax.swing.JComboBox<>();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        joiningDate = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        materialField = new JList<Material>(listModel);

        ;
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setName("showAll"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nuevo ciruja");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        specialtyField.setEditable(true);
        specialtyField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Cartón y papel", "Vidrio", "metales" }));
        specialtyField.setToolTipText("Seleccionar tipo");
        specialtyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialtyFieldActionPerformed(evt);
            }
        });

        nameField.setName("nameField"); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre completo");

        jLabel2.setText("Especialidad");

        jLabel3.setText("Fecha de ingreso");

        joiningDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        joiningDate.setText("dd/mm/aaaa");
        joiningDate.setToolTipText("");
        joiningDate.setInheritsPopupMenu(true);
        joiningDate.setName("joinDate"); // NOI18N
        joiningDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joiningDateActionPerformed(evt);
            }
        });

        materialField.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            {
                setOpaque(true);
            }

            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, java.lang.Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Material) {
                    Material newMaterial = (Material) value;
                    setText(newMaterial.getTipo() + " (" + newMaterial.getPeso() + "kg)");
                }

                return this;
            }
        });
        jScrollPane2.setViewportView(materialField);

        jButton1.setText("Añadir material");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Materiales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(21, 21, 21))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(42, 42, 42))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(joiningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(specialtyField, javax.swing.GroupLayout.Alignment.TRAILING, 0, 301, Short.MAX_VALUE))
                            .addComponent(jButton1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(specialtyField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(joiningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(52, 52, 52)
                .addComponent(jButton2)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void specialtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialtyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialtyFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = nameField.getText();
        String specialty = specialtyField.getSelectedItem().toString();
        String joined = joiningDate.getText();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Calendar calendar = Calendar.getInstance();
        try {
            Date date = dateFormat.parse(joined);
            calendar.setTime(date);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Fecha ingresada incorrectamente");
        }

        ArrayList<Material> materiales = new ArrayList<>();

        int cirujaId = 0;
        try {
            ArrayList<Ciruja> allCirujas = CirujaDAO.getAll();
            cirujaId = allCirujas.get(allCirujas.size() - 1).getId() + 1;
        } catch (Exception e) {
            System.out.println(e);
        }

        //Se crea el ciruja, se mete en el array de cooperativa y se le asigna un carro
        Ciruja ciruja = new Ciruja(specialty, calendar, cirujaId, materiales, name);
        Main.cooperativa.getCirujas().add(ciruja);

        int indiceLocal = Main.cooperativa.getCirujas().size() - 1;

        Carro carro = Main.cooperativa.nuevoCarro(indiceLocal);

        //Se ingresa el ciruja a la base de datos
        try {
            System.out.println("Crear ciruja");
            CirujaDAO.create(ciruja, carro);
        } catch (Exception e) {
            System.out.println("addCiruja: " + e.getMessage());
        }

        //Se crean los materiales pertenecientes a los cirujas en la base de datos.
        for (int i = 0; i < listModel.getSize(); i++) {
            carro.setCargaActual(listModel.getElementAt(i).getPeso());
            try {
                MaterialDAO.create(cirujaId, listModel.getElementAt(i));
                materiales.add(listModel.getElementAt(i));
                CarroDAO.update(cirujaId, carro);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

        ciruja.setMateriales(materiales);

        nameField.setText("");
        specialtyField.setSelectedItem("Ninguna");
        joiningDate.setText("dd/MM/aaaa");
        listModel.clear();
        JOptionPane.showMessageDialog(null, "Ciruja creado con éxito");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void joiningDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joiningDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joiningDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = "";

        if (specialtyField.getSelectedItem() != "Ninguna") {
            input = specialtyField.getSelectedItem().toString();
        } else {
            input = JOptionPane.showInputDialog(null, "Ingrese el tipo de material");
        }

        String weight = JOptionPane.showInputDialog(null, "Ingrese el peso del material");
        double pesoTotal = 0;
        for (int i = 0; i < listModel.getSize(); i++) {
            pesoTotal += listModel.getElementAt(i).getPeso();
        }
        if (pesoTotal + Double.parseDouble(weight) > 200) {
            JOptionPane.showMessageDialog(null, "El material excede la capacidad máxima.\nCapacidad actual: " + (200 - pesoTotal) + "kg");
            weight = "";
        } else {
            pesoTotal = Double.parseDouble(weight);
            if (input.equals("") || weight.equals("")) {
                JOptionPane.showMessageDialog(null, "Datos ingresados incorrectamente, intente de nuevo");
            } else {
                if (pesoTotal <= 200) {
                    listModel.addElement(new Material(Double.parseDouble(weight), input, listModel.getSize()));
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField joiningDate;
    private javax.swing.JList<Material> materialField;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox<String> specialtyField;
    // End of variables declaration//GEN-END:variables

    DefaultListModel<Material> listModel = new DefaultListModel<>();
    MaterialDAO MaterialDAO = new MaterialDAO();
    CirujaDAO CirujaDAO = new CirujaDAO();
    CarroDAO CarroDAO = new CarroDAO();
}
