package Jframes;

import Clases.*;
import persistencia.*;
import Proyecto_p2.Main;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author agusm
 */
public class AllCirujas extends javax.swing.JPanel {

    /**
     * Creates new form AllArtistas
     */
    public AllCirujas() throws Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new JList<Ciruja>(listModel);
 
 ;
        listModel.clear();
        for (Ciruja obj : Main.cooperativa.getCirujas()) {//acá tengo que traer a todos los cirujas
            listModel.addElement(obj);
        }
        visualizar = new javax.swing.JButton();
        liquidar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(389, 381));

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cirujas");

        jList1.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            {
                setOpaque(true);
            }

            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, java.lang.Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Ciruja) {
                    Ciruja newCiruja = (Ciruja) value;//Ver si el nombre de la clase es ciruja
                    setText(newCiruja.getNombre());
                }

                return this;
            }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        visualizar.setText("Ver ciruja");
        visualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActionPerformed(evt);
            }
        });

        liquidar.setText("Liquidar");
        liquidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        liquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(liquidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(visualizar)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActionPerformed

        if (jList1.getSelectedValue() != null) {
            int idCiruja = jList1.getSelectedValue().getId();
            //Necesito tener el indice del ciruja que tiene dicho idCiruja localmente
            int indiceLocal = 0;
            for (int i = 0; i < Main.cooperativa.getCirujas().size(); i++) {
                if (Main.cooperativa.getCirujas().get(i).getId() == idCiruja) {
                    indiceLocal = i;
                }
            }
            Ciruja c = Main.cooperativa.getCirujas().get(indiceLocal);

            Calendar fechaIngreso = c.getFechaIngreso();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");
            String fechaFormateada = formatoFecha.format(fechaIngreso.getTime());

            //No se repinta cuando agrego materiales a un ciruja
            if (jList1.getSelectedValue() != null) {
                String message = "Ciruja: " + idCiruja + "\n"
                        + "Nombre: " + c.getNombre() + "\n"
                        + "Fecha de ingreso: " + fechaFormateada + "\n"
                        + "Especialidad: " + c.getEspecialidad() + "\n";

                //String materiales
                if (!c.getMateriales().isEmpty()) {
                    message += "Materiables recogidos: \n";
                    for (int i = 0; i < c.getMateriales().size(); i++) {
                        message += " -" + c.getMateriales().get(i).getTipo()
                                + " (" + c.getMateriales().get(i).getPeso() + "kg)";
                        if (i != c.getMateriales().size() - 1) {
                            message += ", \n";
                        }
                    }
                }
                JOptionPane.showMessageDialog(null, message);
            }
        }
    }//GEN-LAST:event_visualizarActionPerformed

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained

    }//GEN-LAST:event_jList1FocusGained

    private void liquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liquidarActionPerformed
        Ciruja ciruja = (Ciruja) jList1.getSelectedValue();
        int indiceLocal = 0;
        for (int i = 0; i < Main.cooperativa.getCirujas().size(); i++) {
            if (Main.cooperativa.getCirujas().get(i).getId() == ciruja.getId()) {
                indiceLocal = i;
                System.out.println("Id ciruja: " + i);
            }
        }
        Double sueldo = Main.cooperativa.liquidar(indiceLocal);
        if (sueldo != 0) {
            JOptionPane.showMessageDialog(null, ciruja.getNombre() + " cobró $" + sueldo);
        } else {
            JOptionPane.showMessageDialog(null, ciruja.getNombre() + " no cuenta con materiales");
        }
        addComponents();
    }//GEN-LAST:event_liquidarActionPerformed

    public void addComponents() {
        listModel.clear();
        ArrayList<Ciruja> cirujas = new ArrayList<>();
        try {
            cirujas = CirujaDAO.getAll();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        for (Ciruja obj : cirujas) {
            listModel.addElement(obj);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<Ciruja> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton liquidar;
    private javax.swing.JButton visualizar;
    // End of variables declaration//GEN-END:variables

    DefaultListModel<Ciruja> listModel = new DefaultListModel<>();
    CirujaDAO CirujaDAO = new CirujaDAO();
}
