package Jframes;

import clases.*;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author agusm
 */
public class AllCirujas extends javax.swing.JPanel {

    /**
     * Creates new form AllArtistas
     */
    public AllCirujas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new JList<Ciruja>(listModel);
 
 ;
        for (Ciruja obj : Jframes.Main.cantantes) {//acá tengo que traer a todos los cirujas
            listModel.addElement(obj);
        }
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(389, 381));

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cirujas");

        jList1.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            {
                setOpaque(true);
            }

            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, java.lang.Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Ciruja) {
                    Ciruja newCiruja = (Ciruja) value;//Ver si el nombre de la clase es ciruja
                    setText(newCiruja.nombre);
                }

                return this;
            }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Ver ciruja");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SerCantor cantor = jList1.getSelectedValue();
        String instrumentos = "";
        if (jList1.getSelectedValue() != null) {
            if (jList1.getSelectedValue() instanceof Artista) {
                instrumentos = ((Artista) jList1.getSelectedValue()).getInstrumentos();
            }
            if (jList1.getSelectedValue() instanceof Gallo) {
                instrumentos = ((Gallo) jList1.getSelectedValue()).getInstrumentos();
            }
            if (jList1.getSelectedValue() instanceof Canario) {
                instrumentos = ((Canario) jList1.getSelectedValue()).getInstrumentos();
            }
            if (instrumentos.equals("")) instrumentos = "Ninguno";
            String estadoDeAnimo = cantor.cuando.isAlegria() ? "feliz" : "triste";
            String message = "Nombre: " + cantor.nombre + "\n"
                    + "Tipo de cantante: " + cantor.tipo + "\n"
                    + "A las " + cantor.cuando.horario()
                    + " se encontraba " + estadoDeAnimo + "\n"
                    + "Instrumentos: " + instrumentos;
            JOptionPane.showMessageDialog(null, message);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained

    }//GEN-LAST:event_jList1FocusGained

    public void addComponents() {
        listModel.clear();
        for (SerCantor obj : Main.cantantes) {
            listModel.addElement(obj);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<Ciruja> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    DefaultListModel<SerCantor> listModel = new DefaultListModel<>();
}
