package Jframes;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import Clases.*;
import Proyecto_p2.Main;
import java.util.logging.Level;
import java.util.logging.Logger;
import persistencia.*;
import javax.swing.JOptionPane;

/**
 *
 * @author agusm
 */
public class DeleteCiruja extends javax.swing.JPanel {

    /**
     * Creates new form deleteCantante
     */
    public DeleteCiruja() throws Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws Exception {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        for (Ciruja obj : CirujaDAO.getAll()) {
            listModel.addElement(obj);  
        }  //Acá tengo que recibir de la base de datos a todos los cirujas
        jList1 = new JList<Ciruja>(listModel);
 
 ;
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("deleteCantante"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar");

        jList1.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            {
                setOpaque(true);
            }

            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, java.lang.Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Ciruja) {
                    Ciruja newCiruja = (Ciruja) value;
                    setText(newCiruja.getNombre());
                }

                return this;
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Eliminar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jList1.getSelectedValue() != null) {
            int idCiruja = jList1.getSelectedValue().getId();

            //Necesito tener el indice del ciruja que tiene el idCiruja
            for (int i = 0; i < Main.cooperativa.getCirujas().size(); i++) {
                if (Main.cooperativa.getCirujas().get(i).getId() == (idCiruja - 1)) {
                    Main.cooperativa.getCirujas().remove(i);
                }
            }
            try {
                CirujaDAO.delete(idCiruja);
            } catch (Exception e) {
                System.out.println("error al borrar: " + e.getMessage());
            }
            addComponents();
            this.repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void addComponents() {
        ArrayList<Ciruja> ciruja = new ArrayList<>();
        listModel.clear();
        try {
            ciruja = CirujaDAO.getAll();
        } catch (Exception e) {
            System.out.println("Error al traer todo " + e.getMessage());
        }
        for (Ciruja obj : ciruja) {
            listModel.addElement(obj);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<Ciruja> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    DefaultListModel<Ciruja> listModel = new DefaultListModel<>();
    CirujaDAO CirujaDAO = new CirujaDAO();
}
